### ISSUE TITLE
 read_ahead_kb locked

### ISSUE THREAD

**Issue by jukmisael** [physwizz/a21s#1]
When trying to change read_ahead_kb in HKteaws or any ManagerKernel Nothing happens.
The file is in /sys/block/mmcblk0/queue, the value is locked at 128, even giving Chmod 777, there is no change in value.

All Kernel Manager hangs when disabling ZRam, and it's not possible to change, we can't leave it in LZ4 by default?

**Comment by physwizz** [comment]
Thanks for the feedback.
I'll add that to my list.
What baseband are you on?
https://t.me/a127f_res

**Comment by jukmisael** [comment]
My Base Band and A217MUBU6CUG1, I'm using Variant M Version, I get the System error on Boot but I ignore it (although it would be nice not to see this)

I think allowing the read_ahead_kb change in all mmcblk* would help a lot as we could adapt the CPU count with IO.

I was taking a look at the Source Code just now, I took a look at Energy_Step, it doesn't use Overclock, if I leave Schedutil by default we will be able to keep both Under and Over, my battery is great with that, the small fine adjustments would make it better.

I really appreciate your attention, if possible I would like to participate, I have been a Custom Kernel since my first J7Neo

**Comment by jukmisael** [comment]
In all my devices I use [this](https://forum.xda-developers.com/t/ref-guide-most-up-to-date-guide-on-cpu-governors-i-o-schedulers-and-more.3048957/) table to guide me, maybe it would be interesting to add some things?

Recommendations

Overall:
Interactive (or balanced variants)
zzmoove (default or optimized profile)
Ondemand
PegasusQ (Works well on some older devices)
Impulse

Battery Saving:
Conservative (tuned, or battery saving variants)
Ondemand (tuned, or battery saving variants)
Smartmax
Powersave
Alucard
zzmoove (tuned, change to battery profile)

Performance oriented:
Interactive (tuned, or performance oriented variants)
Intelliactive (preferred over intellidemand)
Performance
Nightmare
Blu_active
Lionheart

In the post itself there are some benchmarks, we can gain more performance and battery.

**Comment by physwizz** [comment]
I don't have this device.
I have a127f. 
Feel free to use my code to further develop the kernel as long as you credit me.
You can post it here.

https://t.me/+19IDHssAXUxjZTI1

**Comment by jukmisael** [comment]
Try changing the read_ahead_kb on your device, I believe it won't change beyond 128 either, it could be a permission issue.

I am grateful for the permission!

**Comment by physwizz** [comment]
I get 8192

**Comment by jukmisael** [comment]
I've tried changing permissions via terminal and even via TWRP, but I still don't understand why it's stuck.
Unfortunately this greatly affects performance.

**Comment by physwizz** [comment]
This is mine
https://t.me/a12schat/1165

**Comment by physwizz** [comment]
Screenshot

**Comment by physwizz** [comment]
https://t.me/a12schat/1165
